'use strict'

// Build-time half of the AOT provider.
//
// The runtime provider compiles each tool's inputSchema on first use, which is
// the right trade on a server and the wrong one on an edge runtime: measured on
// five tool schemas, the runtime path costs 85 KB gzipped and 12 ms of cold
// start, against 0.74 ms for validators compiled ahead of time. A Worker
// isolate cold starts often and per-call microseconds are invisible next to a
// model round trip, so that is the trade that matters there.
//
//   // build step
//   const { compileTools } = require('@ata-project/mcp/build')
//   await compileTools({ tools: { search: searchSchema }, outDir: './compiled' })
//
//   // worker
//   import tools from './compiled/index.mjs'
//   new McpServer(info, { validator: new AtaAotJsonSchemaValidator(tools) })
//
// The lookup is by a hash of the schema rather than by name or by object
// identity. A name has to be kept in step by hand and identity does not
// survive a bundler, while the hash is derived from the thing itself: if the
// schema the server declares is not the schema that was compiled, the lookup
// misses and says so instead of validating against the wrong one.

const fs = require('node:fs')
const path = require('node:path')

// Key ordering is not significant in JSON Schema, so the canonical form sorts
// it. Two schemas that differ only in key order compile to the same validator
// and must hash the same.
function canonical (value) {
  if (Array.isArray(value)) return '[' + value.map(canonical).join(',') + ']'
  if (value && typeof value === 'object') {
    const keys = Object.keys(value).sort()
    return '{' + keys.map((k) => JSON.stringify(k) + ':' + canonical(value[k])).join(',') + '}'
  }
  return JSON.stringify(value === undefined ? null : value)
}

// FNV-1a over the canonical form. Not a security boundary, just a stable key,
// and synchronous everywhere including a Worker, which WebCrypto is not.
function schemaKey (schema) {
  const s = canonical(schema)
  let h = 0x811c9dc5
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h.toString(16).padStart(8, '0') + s.length.toString(16)
}

// compileTools({ tools, outDir, format })
//   tools   { [name]: schema }
//   outDir  where the modules and the index go
//   format  'esm' (default) or 'cjs'
async function compileTools (opts) {
  const tools = (opts && opts.tools) || {}
  const outDir = opts && opts.outDir
  const format = (opts && opts.format) || 'esm'
  if (!outDir) throw new Error('compileTools: outDir is required')

  const { Validator } = require('ata-validator')
  const { toStandaloneModule } = require('ata-validator/aot')

  fs.mkdirSync(outDir, { recursive: true })
  const entries = []
  const declined = []

  for (const [name, schema] of Object.entries(tools)) {
    let source = null
    try {
      source = toStandaloneModule(new Validator(schema), { format })
    } catch (e) {
      declined.push({ name, reason: e.message })
      continue
    }
    if (!source) { declined.push({ name, reason: 'the engine declined to emit a module for this schema' }); continue }
    const file = `${name}.validator.${format === 'cjs' ? 'cjs' : 'mjs'}`
    fs.writeFileSync(path.join(outDir, file), source)
    entries.push({ name, file, key: schemaKey(schema) })
  }

  // The index maps the schema hash to its module, so the runtime never has to
  // be told which tool it is looking at.
  const indexFile = format === 'cjs' ? 'index.cjs' : 'index.mjs'
  const body = format === 'cjs'
    ? entries.map((e) => `const ${safe(e.name)} = require('./${e.file}');`).join('\n') +
      `\nmodule.exports = {\n${entries.map((e) => `  ${JSON.stringify(e.key)}: { name: ${JSON.stringify(e.name)}, module: ${safe(e.name)} },`).join('\n')}\n};\n`
    : entries.map((e) => `import ${safe(e.name)} from './${e.file}';`).join('\n') +
      `\nexport default {\n${entries.map((e) => `  ${JSON.stringify(e.key)}: { name: ${JSON.stringify(e.name)}, module: ${safe(e.name)} },`).join('\n')}\n};\n`
  fs.writeFileSync(path.join(outDir, indexFile),
    '// Generated by @ata-project/mcp. Keyed by a hash of each tool\'s inputSchema.\n' + body)

  return { compiled: entries.map((e) => e.name), declined, index: path.join(outDir, indexFile) }
}

function safe (name) { return '_' + String(name).replace(/[^A-Za-z0-9_]/g, '_') }

module.exports = { compileTools, schemaKey }
